version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-agent-competitors
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      TZ: Asia/Ho_Chi_Minh
    env_file:
      - .env
    volumes:
      - .:/code
    restart: always
